version: "3"
services:
  problemreport:
    image: "diwise/api-problemreport:latest"
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
      - postgresdb
    links:
      - rabbitmq
      - postgresdb
    environment:
      PROBLEMREPORT_DB_HOST: "postgresdb"
      PROBLEMREPORT_DB_USER: "testuser"
      PROBLEMREPORT_DB_NAME: "problemreport"
      PROBLEMREPORT_DB_PASSWORD: "testpass"
      PROBLEMREPORT_DB_SSLMODE: "disable"
      PROBLEMREPORT_API_PORT: "8080"
      RABBITMQ_DISABLED: "true"

    ports:
      - "8088:8080"

  federation:
    image: 'ghcr.io/diwise/api-graphql:prod-10f7bb569256a100d2d6df73c12ddc31c30f14c5'
    restart: always
    depends_on:
      - problemreport
    environment:
      API_GQL_FEDERATION_PORT: '8080'
      API_GQL_FEDERATION_SVCS: 'problemreport:8080'
    ports:
      - '8989:8080'

  postgresdb:
    image: 'ghcr.io/diwise/test-db-postgresql:prod-824e7cffd65dd3766c88441a48cffd5b2acd55f2'
    restart: always
    environment:
      POSTGRES_DB: "problemreport"
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "testpass"
    ports:
      - "5432"
